# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: mysql
  tag: 8.0.22

service:
  type: ClusterIP
  port: 3306

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  volume:
    enabled: true
    claim: 1Gi
    total: 1Gi
    hostpath: "/db/mysql"

storageclass:
  name: mysql-storageclass