{{- if .Values.global.np.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "server.name" . }}-to-mysql-rabbit
spec:
  podSelector:
    matchLabels:
      app: {{ include "server.name" . }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ include "mysql.name" . }}
    ports:
    - port: {{ .Values.global.mysql.port }}
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: {{ include "rabbitmq.name" . }}
    ports:
    - port: {{ .Values.global.rabbit.port }}
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "server.name" . }}-from-ingress
spec:
  podSelector:
    matchLabels:
      app: {{ include "server.name" . }}
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: {{ .Values.server.service.port }}
{{- end }}