apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.service" . }}
  labels:
    app: {{ include "server.name" . }}
    chart: {{ include "server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ include "server.name" . }}
    release: {{ .Release.Name }}
  type: {{ if .Values.ingress.enabled }}ClusterIP{{ else }}{{ .Values.server.service.type }}{{ end }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}
      protocol: TCP
      name: server-port

