{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "server.service" . }}
            port:
              number: {{ .Values.server.service.port }}
      - path: /toposervice/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "toposervice.service" . }}
            port:
              number: {{ .Values.toposervice.service.port }}
{{- end }}