{{- if .Values.global.np.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mongodb.name" . }}-from-planner
spec:
  podSelector:
    matchLabels:
      app: {{ include "weatherservice.name" . }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ include "planner.name" . }}
    ports:
    - port: {{ .Values.weatherservice.service.port }}
      protocol: TCP
{{- end }}