# Default values for eoloplanner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:

  # MySQL
  mysql:
    root_user: root
    root_password: password
    database: eoloplantsDB
    port: 3306

  # Mongodb
  mongo:
    db: topoDB
    db_root_username: root
    db_root_password: password
    port: "27017"
  
  # RabbitMQ
  rabbit:
    default_user: root
    default_password: password
    port: "5672"

  # security context
  securityContext:
    runAsUser: 1001
    
  # network policies
  np:
    enabled: true

ingress:
  enabled: true
  hostname: cluster-ip

weatherservice:
  replicaCount: 1

  image:
    repository: oscarsotosanchez/weatherservice
    tag: "v1.0"

  service:
    type: ClusterIP
    port: 9090

planner:
  replicaCount: 1

  image:
    repository: amartinm82/planner
    tag: "v2.0"

toposervice:
  replicaCount: 1

  image:
    repository: oscarsotosanchez/toposervice
    tag: "v1.0"

  securityContext:
    runAsUser: 1001

  service:
    type: LoadBalancer
    port: 8080

  spring_data_mongodb_authentication_database: admin

server:
  replicaCount: 1

  image:
    repository: oscarsotosanchez/server
    tag: "v1.0"

  service:
    type: LoadBalancer
    port: 3000
