{{- if .Values.global.np.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mongodb.name" . }}-from-topo
spec:
  podSelector:
    matchLabels:
      app: {{ include "mongodb.name" . }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ include "toposervice.name" . }}
    ports:
    - port: {{ .Values.global.mongo.port }}
      protocol: TCP
{{- end }}