{{- if .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
stringData:
  password: {{ default (randAlphaNum 8) .Values.global.mongo.db_root_password }}
{{- end }}