{{- if .Values.global.np.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "toposervice.name" . }}-to-mongodb
spec:
  podSelector:
    matchLabels:
      app: {{ include "toposervice.name" . }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ include "mongodb.name" . }}
    ports:
    - port: {{ .Values.global.mongo.port }}
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "toposervice.name" . }}-from-planner-ingress
spec:
  podSelector:
    matchLabels:
      app: {{ include "toposervice.name" . }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ include "planner.name" . }}
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: {{ .Values.toposervice.service.port }}
{{- end }}