{{- if .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-secret
stringData:
  password: {{ default (randAlphaNum 8) .Values.global.rabbit.default_password }}
{{- end }}