{{- if .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
stringData:
  password: {{ default (randAlphaNum 8) .Values.global.mysql.root_password }}
{{- end }}